


ALLOWED_LIST = ['INTERNET', 'READ_PHONE_STATE', 'ACCESS_NETWORK_STATE', 'ACCESS_COARSE_LOCATION', 'RECEIVE_BOOT_COMPLETED', \
			'ACCESS_FINE_LOCATION', 'ACCESS_WIFI_STATE', 'WRITE_EXTERNAL_STORAGE','launcher.permission.INSTALL_SHORTCUT','GET_ACCOUNTS', \
			'browser.permission.READ_HISTORY_BOOKMARKS','VIBRATE','WAKE_LOCK','launcher.permission.READ_SETTINGS', \
			'browser.permission.WRITE_HISTORY_BOOKMARKS','GET_TASKS','SET_WALLPAPER','WRITE_SETTINGS','READ_EXTERNAL_STORAGE', \
			'vending.BILLING', 'android.c2dm.permission.RECEIVE', 'CAMERA', 'SYSTEM_ALERT_WINDOW', 'RECORD_AUDIO', 'CHANGE_WIFI_STATE']
ALLOWED_LIST.sort()

